server:
  port: 8080

jwt:
  issuer: demo.complitech.by
  secret: cfv223WEDr_vfhSFBG_w3t22
  jwtExpirationMs: 1800000
  jwtRefreshExpirationMs: 172800000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          aut: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      auto-commit: false
      maximum-pool-size: 20
  jpa:
    generate-ddl: false
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl: none